/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#ff5250',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8ea',
        'primary-fixed-dim': '#bcc7de',
        'primary': '#091426',
        'on-background': '#191c1e',
        'secondary-container': '#6cf8bb',
        'surface-dim': '#d8dadc',
        'tertiary-container': '#5a0008',
        'on-surface-variant': '#45474c',
        'on-error': '#ffffff',
        'secondary': '#006c49',
        'outline': '#75777d',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'tertiary': '#330002',
        'outline-variant': '#c5c6cd',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#6ffbbe',
        'inverse-primary': '#bcc7de',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed': '#410004',
        'secondary-fixed-dim': '#4edea3',
        'inverse-surface': '#2d3133',
        'on-secondary-container': '#00714d',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'primary-fixed': '#d8e3fb',
        'on-primary-fixed': '#111c2d',
        'tertiary-fixed': '#ffdad7',
        'surface-container-low': '#f2f4f6',
        'on-secondary-fixed': '#002113',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-primary-fixed-variant': '#3c475a',
        'surface-tint': '#545f73',
        'surface': '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#8590a6',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1e293b',
        'on-tertiary-fixed-variant': '#930013',
        'surface-container-highest': '#e0e3e5',
      },
      spacing: {
        'nav-width': '260px',
        'stack-sm': '8px',
        'stack-xs': '4px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'container-max': '1440px',
        'stack-lg': '24px',
        'stack-md': '16px',
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-tabular': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(30, 41, 59, 0.05)',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
