// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List accounts with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedAccounts"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "description": "Account payload",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Account"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/distributions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "distributions"
                ],
                "summary": "List income distributions (dividends/interest) with pagination and a year summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter to the tax year the income was paid",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a single holding",
                        "name": "holding_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedDistributions"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "distributions"
                ],
                "summary": "Record an income payment by hand",
                "parameters": [
                    {
                        "description": "Distribution payload",
                        "name": "distribution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DistributionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Distribution"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/distributions/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "distributions"
                ],
                "summary": "Delete an income payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Distribution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "distributions"
                ],
                "summary": "Update an income payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Distribution ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Distribution payload",
                        "name": "distribution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DistributionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Distribution"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/holdings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holdings"
                ],
                "summary": "List holdings with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedHoldings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holdings"
                ],
                "summary": "Create a new holding",
                "parameters": [
                    {
                        "description": "Holding payload",
                        "name": "holding",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateHoldingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Holding"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/holdings/allocation": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holdings"
                ],
                "summary": "Portfolio allocation by asset class, and sector within equities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AllocationSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/holdings/backfill-profiles": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holdings"
                ],
                "summary": "Look up reference data for holdings that don't have it yet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/marketdata.BackfillResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/holdings/{id}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holdings"
                ],
                "summary": "Update an existing holding",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holding ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Holding payload",
                        "name": "holding",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateHoldingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Holding"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax-lots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax-lots"
                ],
                "summary": "List tax lots with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a single holding",
                        "name": "holding_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedTaxLots"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Records a stock buy against a holding. The buy transaction is the tax lot.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax-lots"
                ],
                "summary": "Add a tax lot",
                "parameters": [
                    {
                        "description": "Tax lot payload",
                        "name": "tax_lot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateTaxLotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/TaxLotWithTransaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax-lots/{id}": {
            "patch": {
                "description": "Updates the buy transaction behind the lot and recomputes the holding. Rejected if the lot has already been sold from.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax-lots"
                ],
                "summary": "Update a tax lot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tax lot (buy transaction) ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tax lot payload",
                        "name": "tax_lot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTaxLotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TaxLot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "List everything realized in a tax year",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tax year; omit for all years",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "capital_gain | interest | dividend",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "disposal | distribution",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to one security",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to one account",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to one holding",
                        "name": "holding_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedRealizedEvents"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/jurisdictions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "List the tax jurisdictions the app knows about",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TaxJurisdiction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/profiles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "List tax residency profiles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TaxProfile"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Set a user's tax residency",
                "parameters": [
                    {
                        "description": "Tax profile payload",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TaxProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TaxProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/recompute": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Re-evaluate every stored tax treatment against the current rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/rules": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "List tax rules, optionally for one jurisdiction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter to one jurisdiction code (e.g. US-CA)",
                        "name": "jurisdiction",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TaxRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tax/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Taxable income for a year, broken down per jurisdiction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tax year (defaults to the current year)",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TaxSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List transactions with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a single holding",
                        "name": "holding_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedTransactions"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a transaction",
                "parameters": [
                    {
                        "description": "Transaction payload",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "delete": {
                "description": "Soft-deletes the transaction; if it belongs to a holding, the holding's lots and aggregates are rebuilt from its remaining buys and sells. A buy's own lot is not removed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Delete a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates the transaction; if it belongs to a holding, the holding's lots and aggregates are rebuilt from its buys and sells. A buy's own lot is not changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Update a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction payload",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/upload-transactions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload-transactions"
                ],
                "summary": "List upload transactions with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedUploadTransactions"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/uploads": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "List uploads with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginatedUploads"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Routes the file to a handler selected by file_type + account_type (currently: holdings + fidelity)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Upload a data file for import",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to import",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kind of data in the file (e.g. holdings, transactions)",
                        "name": "file_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Institution the file came from (e.g. fidelity)",
                        "name": "account_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account to tie the data to (required for transactions)",
                        "name": "account_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UploadResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Account": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "default_cost_basis": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/User"
                    }
                },
                "tax_type": {
                    "type": "string"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Transaction"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "AllocationSlice": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "percent": {
                    "type": "number"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "AllocationSummary": {
            "type": "object",
            "properties": {
                "asset_classes": {
                    "description": "AssetClasses splits the whole portfolio; EquitySectors splits the equity\npart of it and is weighted within that, since a sector describes a company\nand means nothing for cash or a government bond.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AllocationSlice"
                    }
                },
                "equity_percent": {
                    "type": "number"
                },
                "equity_sectors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AllocationSlice"
                    }
                },
                "equity_value": {
                    "type": "number"
                },
                "total_value": {
                    "type": "number"
                }
            }
        },
        "CapitalSummary": {
            "type": "object",
            "properties": {
                "long_term": {
                    "type": "number"
                },
                "loss_carryforward": {
                    "description": "LossCarryforward is a net loss left over, as a positive number.",
                    "type": "number"
                },
                "net": {
                    "type": "number"
                },
                "offset": {
                    "description": "Offset is how much of one holding period's loss the other's gain absorbed.",
                    "type": "number"
                },
                "short_term": {
                    "type": "number"
                },
                "taxable": {
                    "description": "Taxable is what reaches taxable income: the net when it's a gain, zero\nwhen it's a loss.",
                    "type": "number"
                }
            }
        },
        "CreateAccountRequest": {
            "type": "object",
            "required": [
                "account_name",
                "account_type"
            ],
            "properties": {
                "account_name": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "default_cost_basis": {
                    "type": "string"
                },
                "owner_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tax_type": {
                    "type": "string"
                }
            }
        },
        "CreateHoldingRequest": {
            "type": "object",
            "required": [
                "asset_type",
                "description"
            ],
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "average_cost_basis": {
                    "type": "number"
                },
                "cost_basis_total": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "dividend_income": {
                    "type": "number"
                },
                "issuer_jurisdiction": {
                    "type": "string"
                },
                "last_price": {
                    "type": "number"
                },
                "purchase_quantity": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "tax_class_override": {
                    "description": "TaxClassOverride and IssuerJurisdiction describe the asset's tax\nattributes; nil means \"derive from the asset type\". They replace the old\nstate_tax_exempt flag - what a holding pays and who issued it are facts\nabout the asset, while whether that's exempt is a jurisdiction's rule.",
                    "type": "string"
                }
            }
        },
        "CreateTaxLotRequest": {
            "type": "object",
            "required": [
                "purchase_date",
                "purchase_price",
                "purchase_quantity"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "commission": {
                    "type": "number"
                },
                "fees": {
                    "type": "number"
                },
                "holding_id": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_quantity": {
                    "type": "number"
                }
            }
        },
        "CreateTransactionRequest": {
            "type": "object",
            "required": [
                "action",
                "date"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "action": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_description": {
                    "type": "string"
                },
                "asset_type": {
                    "type": "string"
                },
                "commission": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                },
                "holding_id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "realized_gains": {
                    "type": "number"
                },
                "settlement_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "CreateUserRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "Distribution": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_type": {
                    "type": "string"
                },
                "category": {
                    "description": "Category is the kind of income: \"dividend\" (from a security) or\n\"interest\" (from a cash/savings balance).",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "holding_id": {
                    "description": "HoldingID, Symbol, and AssetType identify the paying security. Symbol and\nAssetType are unset for account-level income like bank interest, and\nHoldingID is nil until a matching holding exists to link to.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payment_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "transaction_id": {
                    "description": "TransactionID is nil for a cash dividend or interest payment. It's reserved\nfor a reinvested dividend, which also opens a buy lot - not handled yet.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "DistributionRequest": {
            "type": "object",
            "required": [
                "account_id",
                "payment_date"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_type": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "holding_id": {
                    "type": "string"
                },
                "payment_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "DistributionSummary": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "number"
                }
            }
        },
        "Holding": {
            "type": "object",
            "properties": {
                "asset_class": {
                    "type": "string"
                },
                "asset_type": {
                    "type": "string"
                },
                "average_cost_basis": {
                    "type": "number"
                },
                "company_name": {
                    "description": "Reference data about the security, from a market-data provider. Purely\ndescriptive - nothing in the portfolio or tax math reads it - so it is\nfilled in when it can be and left empty when it can't.",
                    "type": "string"
                },
                "contract_multiplier": {
                    "description": "ContractMultiplier is how many shares one unit of this holding covers -\n100 for a standard option contract, 1 for everything else. Quoted prices\nare per share, so every basis and proceeds figure scales by it.",
                    "type": "number"
                },
                "cost_basis_total": {
                    "type": "number"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_value": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "dividend_income": {
                    "type": "number"
                },
                "exchange": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "gain_realized_amount": {
                    "type": "number"
                },
                "gain_realized_percent": {
                    "type": "number"
                },
                "gain_unrealized_amount": {
                    "type": "number"
                },
                "gain_unrealized_percent": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "issuer_jurisdiction": {
                    "description": "IssuerJurisdiction is the government that issued this asset's debt, for\nthe bond classes. It's what the tax rules compare against a jurisdiction\nto decide questions like \"did my own state issue this?\" - nil means the\nasset-type default (see defaultIssuerJurisdiction).",
                    "type": "string"
                },
                "last_price": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "option_type": {
                    "description": "\"call\" | \"put\"",
                    "type": "string"
                },
                "profile_fetched_at": {
                    "description": "ProfileFetchedAt records that a lookup happened, whether or not it found\nanything. Without it a symbol the provider doesn't cover - a treasury\nCUSIP, an option contract - would be retried on every pass forever.",
                    "type": "string"
                },
                "purchase_quantity": {
                    "type": "number"
                },
                "sector": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strike_price": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "tax_class": {
                    "description": "TaxClass is the resolved class (override, else the asset-type default),\ncomputed for responses via AfterFind and never persisted. AssetClass is\nthe allocation slice it implies.",
                    "type": "string"
                },
                "tax_class_override": {
                    "description": "TaxClassOverride overrides the tax class implied by the asset type. Nil\nmeans \"derive from the asset type\" (see ResolveTaxClass); a non-nil value\nis an explicit user choice - e.g. a treasury-only ETF like TLT classed as\ngovernment_bond even though ETFs are equity by default.",
                    "type": "string"
                },
                "underlying": {
                    "description": "Option detail, decoded from the contract symbol (see ParseOptionSymbol).\nNil/empty for everything else.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "JurisdictionSummary": {
            "type": "object",
            "properties": {
                "capital": {
                    "description": "Capital and Ordinary are reported apart because they are taxed apart: a\ncapital loss nets against capital gains only, never against interest or\ndividends.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/CapitalSummary"
                        }
                    ]
                },
                "code": {
                    "type": "string"
                },
                "excluded": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaxExclusion"
                    }
                },
                "level": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ordinary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaxBucket"
                    }
                },
                "ordinary_total": {
                    "type": "number"
                },
                "taxable_total": {
                    "type": "number"
                }
            }
        },
        "PaginatedAccounts": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Account"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedDistributions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Distribution"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "summary": {
                    "$ref": "#/definitions/DistributionSummary"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedHoldings": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Holding"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedRealizedEvents": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/RealizedEvent"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "summary": {
                    "$ref": "#/definitions/RealizedEventSummary"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedTaxLots": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaxLot"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedTransactions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Transaction"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedUploadTransactions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UploadTransaction"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PaginatedUploads": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Upload"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "RealizedEvent": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "acquired_date": {
                    "description": "Lot detail, set only for a disposal. Nil on income, which has no lot\nbehind it - distinct from a cost basis that happens to be zero.",
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_type": {
                    "type": "string"
                },
                "category": {
                    "description": "Category is what was realized: IncomeTypeCapitalGain, IncomeTypeInterest,\nor IncomeTypeDividend. Origin is which kind of source produced it.",
                    "type": "string"
                },
                "cost_basis": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "distribution_id": {
                    "type": "string"
                },
                "event_date": {
                    "description": "EventDate is when it was realized - the sell's date, or the payment date.\nOne column for both so the ledger sorts and filters by time as a whole.",
                    "type": "string"
                },
                "holding_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lot_transaction_id": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "proceeds": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "term": {
                    "description": "\"short\" | \"long\"; empty for income",
                    "type": "string"
                },
                "transaction_id": {
                    "description": "Source links. Two real foreign keys rather than a polymorphic pair, so\neach stays a genuine reference the database can enforce. TransactionID is\nthe realizing sell and LotTransactionID the buy that supplied the shares;\nDistributionID is the income record. Exactly one origin's ids are set.",
                    "type": "string"
                },
                "treatments": {
                    "description": "Treatments is how each jurisdiction taxes this event. A real association\nnow that the ledger is one table, so it preloads like any other.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaxTreatment"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "RealizedEventSummary": {
            "type": "object",
            "properties": {
                "capital_gains": {
                    "type": "number"
                },
                "dividends": {
                    "type": "number"
                },
                "interest": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "TaxBucket": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "character": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "TaxExclusion": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "label": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "TaxJurisdiction": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "level": {
                    "description": "national | regional",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_code": {
                    "description": "ParentCode is the jurisdiction this one sits inside, nil for a national\njurisdiction.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "TaxLot": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "asset_description": {
                    "type": "string"
                },
                "asset_type": {
                    "type": "string"
                },
                "contract_multiplier": {
                    "type": "number"
                },
                "cost_basis": {
                    "description": "CostBasis is the open part of the lot at its opening price, commission\nand fees included - negative for a short lot, where the premium came in.",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "direction": {
                    "description": "Direction is \"long\" or \"short\"; a written option's lot took premium in\nrather than paying it out, so its figures carry the opposite sign.",
                    "type": "string"
                },
                "gain_unrealized_amount": {
                    "type": "number"
                },
                "gain_unrealized_percent": {
                    "type": "number"
                },
                "holding_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_price": {
                    "type": "number"
                },
                "market_value": {
                    "description": "MarketValue and the unrealized figures are nil when the holding has no\nprice: an unpriced lot has an unknown value, not a value of zero, and\nreporting zero would show the whole basis as a loss.",
                    "type": "number"
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_quantity": {
                    "type": "number"
                },
                "remaining_quantity": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "TaxLotWithTransaction": {
            "type": "object",
            "properties": {
                "tax_lot": {
                    "$ref": "#/definitions/TaxLot"
                },
                "transaction": {
                    "$ref": "#/definitions/Transaction"
                }
            }
        },
        "TaxProfile": {
            "type": "object",
            "properties": {
                "country_code": {
                    "description": "CountryCode is the national jurisdiction's code; RegionCode the regional\none, nil where the country has no regional income tax or the person isn't\nsubject to one.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "effective_from": {
                    "description": "EffectiveFrom is when this residency started. Only the current profile is\nconsulted today; storing the date means a residency history can be added\nlater without a migration.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "region_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "TaxProfileRequest": {
            "type": "object",
            "required": [
                "country_code",
                "user_id"
            ],
            "properties": {
                "country_code": {
                    "type": "string"
                },
                "region_code": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "TaxRule": {
            "type": "object",
            "properties": {
                "asset_tax_class": {
                    "type": "string"
                },
                "character": {
                    "description": "Stored as tax_character: \"character\" is a type name in Postgres and can't\nbe used unquoted as a column.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "income_type": {
                    "description": "Match columns. Empty string = matches anything.",
                    "type": "string"
                },
                "issuer_scope": {
                    "description": "see IssuerScope* above",
                    "type": "string"
                },
                "jurisdiction_code": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "priority": {
                    "description": "Priority orders the match; highest wins. Reason is the machine-readable\nlabel carried onto the resulting treatment so the UI can explain an\nexclusion (\"Excluded - U.S. Treasury interest\").",
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "term": {
                    "description": "short | long, capital gains only",
                    "type": "string"
                },
                "treatment": {
                    "description": "Outcome.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "TaxSummary": {
            "type": "object",
            "properties": {
                "jurisdictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/JurisdictionSummary"
                    }
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "TaxTreatment": {
            "type": "object",
            "properties": {
                "character": {
                    "description": "Stored as tax_character: \"character\" is a type name in Postgres and can't\nbe used unquoted as a column.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "excluded_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "jurisdiction_code": {
                    "type": "string"
                },
                "realized_event_id": {
                    "description": "RealizedEventID is a real foreign key: one ledger means this can be a\nplain association rather than a polymorphic (type, id) pair, so treatments\npreload with their events instead of being stitched together by hand.",
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "rule_id": {
                    "description": "RuleID is the rule that decided this, nil when no rule was consulted (a\nsheltered account) or none matched. Reason is its machine-readable label.",
                    "type": "string"
                },
                "tax_year": {
                    "description": "TaxYear is denormalized from the event so a year's per-jurisdiction\nsummary stays a single grouped query with no join. It's rewritten with the\ntreatment, so it can't drift from the event it came from.",
                    "type": "integer"
                },
                "taxable": {
                    "type": "boolean"
                },
                "taxable_amount": {
                    "description": "TaxableAmount and ExcludedAmount split the event's amount by this\njurisdiction's treatment; exactly one is non-zero. Keeping the excluded\nside rather than dropping it is what lets the UI show what was left out\n(\"Excluded - U.S. Treasury interest\") instead of a silently smaller total.",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Transaction": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "action": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_description": {
                    "type": "string"
                },
                "asset_type": {
                    "type": "string"
                },
                "commission": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "effect": {
                    "description": "Effect and Direction describe what a trade does to the lot ledger, which\nthe action alone can't say once options are involved: writing an option\nOPENS a position by selling, and buying it back CLOSES one.\n\nEffect is \"open\" (creates a lot) or \"close\" (depletes lots); Direction is\n\"long\" or \"short\", saying which side the lot sits on. A stock buy is an\nopen/long and a stock sell a close/long, so the existing behaviour is just\nthe ordinary case of the same rule. Empty on non-lot actions.",
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                },
                "holding_id": {
                    "description": "HoldingID is nil until a matching Holding exists to link to - imported\ntransactions and holdings come from separate Fidelity exports and may\nnot arrive in the same order.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "realized_gains": {
                    "type": "number"
                },
                "remaining_quantity": {
                    "description": "RemainingQuantity is set only on a stock buy, which doubles as a tax lot:\nit's the shares of this purchase still open (quantity minus what later\nsells have disposed). Nil for sells and other actions. Maintained as a\ncache by the recompute; the Gain ledger is the source of truth.",
                    "type": "number"
                },
                "settlement_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "UpdateHoldingRequest": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "average_cost_basis": {
                    "type": "number"
                },
                "cost_basis_total": {
                    "type": "number"
                },
                "current_value": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "dividend_income": {
                    "type": "number"
                },
                "issuer_jurisdiction": {
                    "type": "string"
                },
                "last_price": {
                    "type": "number"
                },
                "purchase_quantity": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "tax_class_override": {
                    "type": "string"
                }
            }
        },
        "UpdateTaxLotRequest": {
            "type": "object",
            "required": [
                "purchase_date",
                "purchase_price",
                "purchase_quantity"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_price": {
                    "type": "number"
                },
                "purchase_quantity": {
                    "type": "number"
                }
            }
        },
        "UpdateTransactionRequest": {
            "type": "object",
            "required": [
                "action",
                "date"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "action": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "commission": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                }
            }
        },
        "Upload": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "start_date": {
                    "description": "StartDate and EndDate bound the dates of the transactions in the file, so\nwe know the range covered. Nil until the file is parsed.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "UploadResult": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "duplicates": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "UploadTransaction": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "asset_description": {
                    "type": "string"
                },
                "asset_type": {
                    "type": "string"
                },
                "commission": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "distribution_id": {
                    "type": "string"
                },
                "fees": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "realized_gains": {
                    "type": "number"
                },
                "settlement_date": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "transaction_id": {
                    "description": "A row links to exactly one of the domain records the import produced: a\nTransaction (trades) or a Distribution (dividends/interest). Both are\nnullable so either kind can be absent; a transaction still has 0 or 1\nupload_transaction (the unique index treats NULLs as distinct, so many\ndistribution rows can share a NULL transaction_id).",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "upload_id": {
                    "description": "UploadID ties this row to the file import it came from.",
                    "type": "string"
                }
            }
        },
        "User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "marketdata.BackfillResult": {
            "type": "object",
            "properties": {
                "considered": {
                    "type": "integer"
                },
                "enriched": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "not_found": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "My Portfolio API",
	Description:      "Portfolio tracking API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
